### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by christianwiedemann** [wingsuit-designsystem/wingsuit#62]
Roadmap:

- [x] Docs: Pattern documentation
- [x] Docs: Starterkit
- [x] Fix javascript reload issues.
- [x] Docs: Review
- [x] Finalize Landingpage
- [x] Finalize Bootstrap Starterkit
- [x] Finalize Menu 
- [x] Startpage
- [x] Component: Review Grid
- [x] Docs: Layout
- [x] Wingsuit kickstarter
- [x] Component: Button
- [x] Finalize Layout builder UI
- [x] Switch to controls
